# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  cloudclipapi:
    image: cloudclipapi
    build:
      context: .
      dockerfile: CloudClip.API/Dockerfile
    ports:
      - 5136:5136
